routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    //return view('welcome');
	$url = "/pessoas";
	return Redirect::intended($url);
});

//Route::get('pessoas/search', 'PessoasController@search');

Route::resource('pessoas', 'PessoasController');
Route::any('pessoas/search', array('uses' => 'PessoasController@search', 'as' => 'pessoas.search'));
Route::post('pessoas/telefone', array('uses' => 'PessoasController@telefone', 'as' => 'pessoas.telefone'));


Route::resource('telefones', 'TelefonesController');
Route::get('telefones/{id}/lista', array('uses' => 'TelefonesController@lista', 'as' => 'telefones.lista'));
Route::get('telefones/{id}/delete', array('uses' => 'TelefonesController@delete',   'as' => 'telefones.delete'));

app/Pessoa.php
<?php 

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Jenssegers\Date\Date;
use App\Http\Controllers\DateTimes;

class Pessoa extends Model {

    protected $table = 'pessoas';

    public $timestamps = false;

    protected $fillable = [
        'nome', 'cpf', 'email', 'data_nascimento',
    ];

    public function formatedCreatedDataNascimento()
    {
        if ($this->dataNascimento) {
            //return Date::parse($this->dataNascimento)->format('d/m/Y');
        }
    } 

    public function setDataNascimentoAttribute($data_nascimento)
    {
        //$this->attributes['dataNascimento'] = Date::parse($data_nascimento)->format('Y-m-d');
        $data_nascimento = implode('-', array_reverse(explode('/', $data_nascimento)));
        $this->attributes['data_nascimento'] = ($data_nascimento);
    }    

    public function setCpfAttribute($cpf)
    {
        $cpf = str_replace(".", "", $cpf);
        $this->attributes['cpf'] = str_replace("-", "", $cpf);
    } 

    public function formatedDataNascimento()
    {
        if ($this->data_nascimento) {
            return Date::parse($this->data_nascimento)->format('d/m/Y');
        } else {
            return "";
        }
    }

    public function idade()
    {
        if ($this->data_nascimento) {
            // Declara a data! :P
            $data = $this->data_nascimento;
           
            // Separa em dia, mês e ano
            list($ano, $mes, $dia) = explode('-', $data);
           
            // Descobre que dia é hoje e retorna a unix timestamp
            $hoje = mktime(0, 0, 0, date('m'), date('d'), date('Y'));
            // Descobre a unix timestamp da data de nascimento do fulano
            $nascimento = mktime( 0, 0, 0, $mes, $dia, $ano);
           
            // Depois apenas fazemos o cálculo já citado :)
            $idade = floor((((($hoje - $nascimento) / 60) / 60) / 24) / 365.25);

            if($idade > 1){
                $complemento = " anos";
            } else {
                $complemento = " ano";
            }
            return $idade . $complemento;
            
        } else {
            return "";
        }
    }    

    public function formatedCpf()
    {

        if (strlen($this->cpf) === 11) {
            return preg_replace("/(\d{3})(\d{3})(\d{3})(\d{2})/", "\$1.\$2.\$3-\$4", $this->cpf);
        }

        return $this->cpf;
    }

    public function setCpfAtAttribute($cpf)
    {
        $this->attributes['cpd'] = Carbon::createFromFormat('Y-m-d', $cpf);
    }

    public function telefone()
    {
        return $this->hasOne('App\Telefone', 'idpessoa');
    }

}

app/Http/Controllers/PessoasController.php
<?php

namespace App\Http\Controllers;

use App\User;
use App\Pessoa;
use App\Telefone;
use Illuminate\Http\Request;

use Jenssegers\Date\Date;

class PessoasController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */


    public function __construct(Pessoa $pessoa, Telefone $telefone)
    {

        $this->pessoa   = $pessoa;
        $this->telefone = $telefone;
    }

    public function index()
    {

        $pessoas = $this->pessoa->with('telefone')->orderBy('nome', 'asc')->get();
        //dd(count($pessoas[1]->telefone()));
        return view('pessoas.index', compact('pessoas'));
    }

    public function search(Request $request)
    {

        if($request->nome){
            $pessoas = $this->pessoa->where('nome', 'like', '%'.$request->nome.'%')->orderBy('nome', 'asc')->get();
        } else if($request->cpf){
            $cpf = str_replace(".", "", $request->cpf);
            $cpf = str_replace("-", "", $cpf);
            //echo $cpf; die;
            $pessoas = $this->pessoa->where('cpf', 'like', '%'.$cpf.'%')->orderBy('cpf', 'asc')->get();
        } else {
            $pessoas = $this->pessoa->orderBy('cpf', 'asc')->get();
        }

        return view('pessoas.index', compact('pessoas'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {        

        return view('pessoas.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $pessoa = new Pessoa();

        $pessoa->nome       = $request->input("nome");
        $pessoa->cpf        = $request->input("cpf");
        $pessoa->email      = $request->input("email");
        $pessoa->dataNascimento  = $request->data_nascimento;
        $pessoa->telefones  = 1;

        $pessoa->save();
   
        $contatos = $request->contato;

        $c = 0;

        foreach ($contatos as $k => $v) {
            if(!empty($contatos['ddd'][$c])) {
                $telefone = new Telefone(); 
                $telefone->ddd      = $contatos['ddd'][$c];
                $telefone->numero   = $contatos['telefone'][$c];
                $telefone->idpessoa = $pessoa->id;

                $telefone->save();

                $c++;
            }
        }


        return redirect()->route('pessoas.index')->with('message', 'Cadastro criado com sucesso.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {


        $pessoa = Pessoa::findOrFail($id);

        $telefones = Telefone::where('idpessoa', $id)->get();

        return view('pessoas.edit', compact('pessoa', 'telefones'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */

    public function update(Request $request, $id)
    {

        $pessoa = $this->pessoa->findOrFail($id);
        
        $pessoa->nome = $request->input("nome");
        $pessoa->cpf  = $request->input("cpf");
        
        $pessoa->dataNascimento  = $request->data_nascimento;
        //dd(Date::parse($request->input("dataNascimento"))->format('Y-m-d'));
        $data = implode('-', array_reverse(explode('/', $request->dataNascimento)));
        //printf($data); die;
        //$request->dataNascimento = date("Y-m-d", strtotime($request->dataNascimento));
        $pessoa->data_nascimento = $data;
        
        $pessoa->email  = $request->input("email");
//dd($pessoa); die;
        $pessoa->save();

        $contatos = @$request->contato;

        $c = 0;
        
        //dd($pessoa); die;

        if($contatos) {
            foreach ($contatos as $k => $v) {
                if(!empty($contatos['ddd'][$c])) {
                    $telefone = new Telefone();
                    $telefone->ddd      = $contatos['ddd'][$c];
                    $telefone->numero   = $contatos['telefone'][$c];
                    $telefone->idpessoa = $id;
                    
                    $c++;
                    $telefone->save();
                }
            }
        }

        return redirect()->route('pessoas.index')->with('message', 'Pessoa atualizado com sucesso.');
    }
    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $pessoa = $this->pessoa->findOrFail($id);

        
        $pessoa->delete();

        $pessoas = $this->pessoa->orderBy('nome', 'asc')->get();

        return redirect()->route('pessoas.index', 'pessoas')->with('message', 'Pessoa deletado com sucesso.');
    }

    public function telefone(Request $request)
    {

        $telefone = new Telefone();

        $telefone->ddd      = $request->input("ddd");
        $telefone->numero   = $request->input("numero");
        $telefone->idpessoa = $request->input("id");
        $telefone->save();
        
        return redirect()->route('pessoas.index')->with('message', 'Telefone adicionado com sucesso.');
    }

}

resources/views/pessoas/create.blade.php
@extends('layouts.app')

@section('content')

    <div class="row">
        <div class="col-sm-12">

            <div class="panel panel-default">
                <div class="panel-heading">
                    <h2 class="panel-title"><i class="fa-user"></i> Cadastro de Pessoa</h2>
                </div>

                <div class="panel-body">

                    <form name="formCadastro" id="formCadastro" method="POST" action="{{ URL::to('pessoas') }}" role="form" class="validate">
                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                            <div class="row">
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label class="control-label">Nome</label>
                                        <input autofocus tabindex="1" type="text" class="form-control" id="nome" name="nome" placeholder="" data-validate="required" data-message-required="Campo nome obrigatório.">
                                    </div>
                                </div>

                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label class="control-label">CPF</label>
                                        <input tabindex="2" type="text" class="form-control" id="cpf" name="cpf" value="" data-validate="required" data-message-required="Campo cpf obrigatório.">
                                    </div>
                                </div>

                            </div>
                            <div class="row">

                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label class="control-label">Email</label>
                                        <input tabindex="3" type="text" class="form-control" name="email" value="" data-validate="required" data-message-required="Campo email obrigatório." >
                                    </div>
                                </div>

                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label class="control-label">Data de Nascimento</label>
                                        <input tabindex="4" type="text" class="form-control" id="dataNascimento" name="data_nascimento" value="" data-validate="required" data-message-required="Campo data de Nascimento obrigatório." >
                                    </div>
                                </div>                                
                            </div>
                        <fieldset style="border: 0px solid #ccc; " >
                            <legend>Contato: </legend>
                            <div class="row">
                                <div class="col-md-1">
                                    <div class="form-group">
                                        <label class="control-label">DDD</label>
                                        <input autofocus type="text" class="form-control" id="ddd" name="ddd[]" placeholder="" data-validate="required" data-message-required="Campo nome obrigatório.">
                                    </div>
                                </div>

                                <div class="col-md-2">
                                    <div class="form-group">
                                        <label class="control-label">Telefone</label>
                                        <input type="text" class="form-control maskFone" id="telefone" name="telefone[]" value="" data-validate="required" data-message-required="Campo login obrigatório.">
                                    </div>
                                </div>
                            
                                <div class="form-group">
                                    <button type="button" id="add-campo" class="btn btn-success pull-left" style="margin-top: 30px;">+</button>
                                </div>

                            </div>

                            <div>
                                <table id="itineraries-table" class="table table-bordered table-striped table-bordered" cellspacing="0" width="100%">
                                    <thead>
                                        <tr>
                                            <th>DDD</th>
                                            <th>Numero</th>
                                            <th>Ações</th>
                                        </tr>
                                    </thead>
                                    <tfoot>
                                        <tr>
                                            <th>DDD</th>
                                            <th>Numero</th>
                                            <th>Ações</th>
                                        </tr>
                                    </tfoot>

                                    <tbody id="formulario" > 

                                    </tbody>
                                </table>
                            </div>

                            <div class="row">                                
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <input tabindex="5" type="submit" value="cadastrar" class="btn btn-success pull-left" />
                                    </div>
                                </div>
                            </div>
                        </fieldset>
                    </form>
                </div>
            </div>
        </div>
    </div>
    
    <script type="text/javascript">
            
        $('#add-campo').click(function() {
            var ddd      = $("#ddd").val();
            var telefone = $("#telefone").val();
            if(ddd) { 
                $('#formulario').append('<tr> <td> '+ddd+' <input hidden type="text" class="form-control" name="contato[ddd][]" value="'+ddd+'"  placeholder="" data-validate="required" data-message-required="Campo nome obrigatório."></td> <td> '+telefone+' <input hidden type="text" class="form-control" name="contato[telefone][]" value="'+telefone+'" data-validate="required" data-message-required="Campo nome obrigatório."> </td> <td style="width: 260px" > <button type="submit" class="btn btn-xs btn-danger btnExcluir"> <i class="glyphicon glyphicon-trash"></i> Delete </button> </td> </tr>');

                $(".btnExcluir").bind("click", Excluir);
                $("#ddd").val("");
                $("#telefone").val("");
            }
        });

        function Excluir(){
            var par = $(this).parent().parent(); //tr
            par.remove();
        };

    </script>

@endsection

resources/views/pessoas/edit.blade.php
@extends('layouts.app')

@section('content')

    <div class="row">
        <div class="col-sm-12">

            <div class="panel panel-default">
                <div class="panel-heading">
                    <h2 class="panel-title"><i class="fa-user"></i> Editando dados de Pessoa</h2>
                </div>

                <div class="panel-body">

                    <form method="POST" action="{{ route('pessoas.update', $pessoa->id) }}" role="form" class="validate">
                        <input type="hidden" name="_method" value="PUT">
                        <input type="hidden" id="_token" name="_token" value="{{ csrf_token() }}">
                        <input type="hidden" name="id" id="id" value="{{ $pessoa->id }}">
                        <div class="row">
                            <div class="col-md-3">
                                <div class="form-group">
                                    <label class="control-label">Nome</label>
                                    <input autofocus tabindex="1" type="text" class="form-control" id="nome" name="nome" placeholder="" data-validate="required" value="{{ $pessoa->nome }}" data-message-required="Campo nome obrigatório.">
                                </div>
                            </div>

                            <div class="col-md-3">
                                <div class="form-group">
                                    <label class="control-label">CPF</label>
                                    <input tabindex="2" type="text" class="form-control" id="cpf" name="cpf" value="{{ $pessoa->formatedCpf() }}" data-validate="required" data-message-required="Campo login obrigatório.">
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-3">
                                <div class="form-group">
                                    <label class="control-label">Email</label>
                                    <input tabindex="3" type="email" class="form-control" name="email" value="{{ $pessoa->email }}" data-validate="required" value="{{ $pessoa->email }}" data-message-required="Campo email obrigatório." >
                                </div>
                            </div>

                            <div class="col-md-3">
                                <div class="form-group">
                                    <label class="control-label">Data de Nascimento</label>
                                    <input tabindex="4" type="dataNascimento" class="form-control" id="dataNascimento" name="dataNascimento" value="{{ $pessoa->formatedDataNascimento() }}" data-validate="required" data-message-required="Campo Data de Nascimento obrigatório." >
                                </div>
                            </div>                                
                        </div>

                        <fieldset style="border: 0px solid #ccc; " >
                            <legend>Contato: </legend>
                            <div class="row">
                                <div class="col-md-1">
                                    <div class="form-group">
                                        <label class="control-label">DDD</label>
                                        <input autofocus type="text" class="form-control" id="ddd" name="ddd[]" placeholder="" data-validate="required" data-message-required="Campo nome obrigatório.">
                                    </div>
                                </div>

                                <div class="col-md-2">
                                    <div class="form-group">
                                        <label class="control-label">Telefone</label>
                                        <input type="text" class="form-control maskFone" id="telefone" name="telefone[]" value="" data-validate="required" data-message-required="Campo login obrigatório.">
                                    </div>
                                </div>
                            
                                <div class="form-group">
                                    <button type="button" id="add-campo" class="btn btn-success pull-left" style="margin-top: 30px;">+</button>
                                </div>

                            </div>
</form>
                            <div>
                                <table id="itineraries-table" class="table table-dark table-bordered table-striped table-bordered" cellspacing="0" width="100%">
                                    <thead>
                                        <tr>
                                            <th>DDD</th>
                                            <th>Numero</th>
                                            <th>Ações</th>
                                        </tr>
                                    </thead>
                                    <tfoot>
                                        <tr>
                                            <th>DDD</th>
                                            <th>Numero</th>
                                            <th>Ações</th>
                                        </tr>
                                    </tfoot>

                                    <tbody id="formulario" > 
                                        @foreach($telefones as $telefone)
                                        <tr class="row-{{$telefone->id}}" >
                                            <td>{{ $telefone->formatedDddd() }}</td>
                                            <td>{{ $telefone->numero }}</td>
                                            <td style="width: 260px" class="text-left" >
                                                <a class="btn btn-xs btn-danger" 
                                                onclick="if(confirm('Deseja realmente excluir?')) { deleteTelefone({{$telefone->id}}); } else {return false };" >
                                                <i class="glyphicon glyphicon-remove"></i> Excluir</a>
                                            </td>
                                        </tr>
                                        @endforeach 
                                    </tbody>
                                </table>
                            </div>

                            <div class="row">                                
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <input tabindex="5" type="submit" value="Atualizar" class="btn btn-success pull-left" />
                                    </div>
                                </div>
                            </div>
                        </fieldset>
                    
                </div>
            </div>
        </div>
    </div>
    
<script type="text/javascript">
            
$('#add-campo').click(function() {
    var ddd      = $("#ddd").val();
    var telefone = $("#telefone").val();
    if(ddd) {         $('#formulario').append('<tr> <td> '+ddd+' <input hidden type="text" class="form-control" name="contato[ddd][]" value="'+ddd+'"  placeholder="" data-validate="required" data-message-required="Campo nome obrigatório."></td> <td> '+telefone+' <input hidden type="text" class="form-control" name="contato[telefone][]" value="'+telefone+'" data-validate="required" data-message-required="Campo nome obrigatório."> </td> <td style="width: 260px" > <button type="submit" class="btn btn-xs btn-danger btnExcluir"> <i class="glyphicon glyphicon-trash"></i> Delete </button> </td> </tr>');

        $(".btnExcluir").bind("click", Excluir);
            var ddd      = $("#ddd").val("");
            var telefone = $("#telefone").val("");
    }
});

function Excluir(){
    var par = $(this).parent().parent(); //tr
    par.remove();
};

function deleteTelefone(id){
    var idTelefone = id;
    $.get("/telefones/"+id+"/delete", 
        { _token: $('#_token').val(), id: idTelefone },
        function(data) {
            $("#formulario").html("");
            listaTelefones($('#id').val());
        });
}

function listaTelefones(id) {
    var idTelefone = id;
    $("#formulario").load("/telefones/"+idTelefone+"/lista");
}

</script>

@endsection

resources/views/pessoas/index.blade.php
@extends('layouts.app')

@section('content')

    <h1>Listagem de Pessoas</h1> 


<div class="panel-body">

    <form method="POST" action="{{ URL::to('pessoas/search') }}" role="form" class="validate">
        <input type="hidden" name="_token" value="{{ csrf_token() }}">
            <div class="row">
                <div class="col-md-3">
                    <div class="form-group">
                        <label class="control-label">Nome</label>
                        <input autofocus tabindex="1" type="text" class="form-control" id="nome" name="nome" placeholder="" data-validate="required" value="" data-message-required="Campo nome obrigatório.">
                    </div>
                </div>

                <div class="col-md-3">
                    <div class="form-group">
                        <label class="control-label">CPF</label>
                        <input tabindex="2" type="text" class="form-control" name="cpf" value="" data-validate="required" value="" data-message-required="Campo login obrigatório.">
                    </div>
                </div>
            
                <div class="col-md-2">
                    <div class="form-group">
                        <input tabindex="3" type="submit" value="pesquisar" class="btn btn-success pull-left" />
                    </div>
                </div>

                <div class="col-md-2">
                    <div class="form-group">
                        <a tabindex="3" href="{{ URL::to('pessoas/create') }}" class="btn btn-primary" >Cadastrar</a>
                    </div>
                </div>

                
            </div>
    </form>

    <table id="itineraries-table" class="table table-striped table-bordered" cellspacing="0" width="100%">
        <thead>
            <tr>
                <th>Nome</th>                                
                <th>Email</th>
                <th>CPF</th>
                <th>Idade</th>
                <th>Qtd de Telefones</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tfoot>
            <tr>
                <th>Nome</th>                                
                <th>Email</th>
                <th>CPF</th>
                <th>Idade</th>
                <th>Qtd de Telefones</th>
                <th>Ações</th>
            </tr>
        </tfoot>

        <tbody>
        @if(count($pessoas))
            @foreach($pessoas as $pessoa)
            <tr>
                <td>{{ $pessoa->nome }}</td>
                <td>{{ $pessoa->email }}</td>
                <td>{{ $pessoa->formatedCpf() }}</td>
                <td>{{ $pessoa->formatedDataNascimento() }}</td>
                <td>{{ $pessoa->telefone()->count() }}</td>
                <td style="width: 160px;" class="text-left" >
                    <a href="/pessoas/{{$pessoa->id}}/edit" class="btn btn-sm btn-success btn-icon" >
                        Editar 
                    </a> 
                    
                    <form style="float: right;" action="{{ URL::to('/pessoas', $pessoa->id) }}" method="POST" >
                        <input type="hidden" name="_method" value="DELETE">
                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                        <button type="submit" class="btn btn-sm btn-danger">Delete</button>
                    </form>
                </td>
            </tr>
            @endforeach 
        @else 
            <tr>
                <td colspan="6" >Nenhum registro encontrado.</td>
            </tr>
        @endif 
        </tbody>
    </table>

</div>
@endsection